import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className="font-serif antialiased bg-[url('https://images.pexels.com/photos/18495/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')]   bg-cover bg-center bg-fixed  bg-no-repeat   
     md:justify-center flex   relative  max-sm:flex max-sm:items-center max-sm:pt-[3rem] ">
        {children}</body>
    </html>
  )
}
